import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbars } from "./components/navbar/Navbars";
import Footers from "./components/footer/Footer";
import Providers from "./providers/Providers";
import "react-toastify/dist/ReactToastify.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <head></head>

        <body
          className={`${inter.className} dark`}
          // suppressHydrationWarning={true}
        >
          <Navbars />

          {children}

          <Footers />
        </body>
      </html>
    </Providers>
  );
}
